server {
    listen 80;
    server_name dexity.mvladt.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dexity.mvladt.ru;

    ssl_certificate     /etc/letsencrypt/live/dexity.mvladt.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dexity.mvladt.ru/privkey.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options    "nosniff" always;
    add_header X-Frame-Options           "DENY" always;
    add_header Content-Security-Policy   "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'" always;

    location / {
        root /var/www/dexity/client/dist;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_buffering           off;
        proxy_cache               off;
        proxy_read_timeout        300s;
        proxy_set_header          Connection '';
        chunked_transfer_encoding on;
    }
}
